name: Github action

on: push

jobs:
  build:
    name: Running Hello World
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2      
      - name: install cpp
        run: sudo apt install -y libcppunit-dev
      - name: run
        run: g++ -o HelloWorld HelloWorld.cpp && .\HelloWorld
