name: Github action

on: push

jobs:
  build:
    name: Running Hello World
    runs-on: ubuntu-latest
    
    steps:
      - name: compiler version
        run: |
            gcc --version
            g++ --version
      - uses: actions/checkout@v2      
      - name: run
        run: cd .github/workflows && g++ -o HelloWorld HelloWorld.cpp && .\HelloWorld
