name: Github action

on: push

jobs:
  build:
    name: Running Hello World
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: complie Hello World
        run: g++ -o HelloWorld HelloWorld.cpp && .\HelloWorld
